name: Run ADO to GitHub Sync with PowerShell

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
             .\SynADOtoGitHub.ps1 -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }}
